<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="HSUVModel" nsURI="http:///HSUVModel.ecore" nsPrefix="HSUVModel">
  <eSubpackages name="HSUVUseCases" nsURI="http:///HSUVModel/HSUVUseCases.ecore" nsPrefix="HSUVModel.HSUVUseCases"/>
  <eSubpackages name="HSUVBehavior" nsURI="http:///HSUVModel/HSUVBehavior.ecore" nsPrefix="HSUVModel.HSUVBehavior">
    <eSubpackages name="DeliverPowerBehavior" nsURI="http:///HSUVModel/HSUVBehavior/DeliverPowerBehavior.ecore"
        nsPrefix="HSUVModel.HSUVBehavior.DeliverPowerBehavior"/>
  </eSubpackages>
  <eSubpackages name="HSUVStructure" nsURI="http:///HSUVModel/HSUVStructure.ecore"
      nsPrefix="HSUVModel.HSUVStructure">
    <eClassifiers xsi:type="ecore:EClass" name="AutomotiveDomain"/>
    <eClassifiers xsi:type="ecore:EClass" name="HybridSUV">
      <eStructuralFeatures xsi:type="ecore:EReference" name="powerSubsystem" ordered="false"
          lowerBound="1" eType="#//HSUVStructure/PowerSubSystem" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="breakSubsystem" ordered="false"
          lowerBound="1" eType="#//HSUVStructure/BreakSubsystem" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="bodySubsystem" ordered="false"
          lowerBound="1" eType="#//HSUVStructure/BodySubsystem" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="interiorSubsystem" ordered="false"
          lowerBound="1" eType="#//HSUVStructure/InteriorSubsystem" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="lightingSubsystem" ordered="false"
          lowerBound="1" eType="#//HSUVStructure/LightingSubsystem" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="chassisSubsystem" ordered="false"
          lowerBound="1" eType="#//HSUVStructure/ChassisSubsytem" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PowerSubSystem">
      <eStructuralFeatures xsi:type="ecore:EReference" name="wheelHubAssembly" ordered="false"
          lowerBound="2" upperBound="2" eType="#//HSUVStructure/WheelHubAssembly"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="brakePedal" ordered="false"
          lowerBound="1" eType="#//HSUVStructure/BrakePedal"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="WheelHubAssembly"/>
    <eClassifiers xsi:type="ecore:EClass" name="BrakePedal"/>
    <eClassifiers xsi:type="ecore:EClass" name="BreakSubsystem">
      <eStructuralFeatures xsi:type="ecore:EReference" name="brakePedal" ordered="false"
          lowerBound="1" eType="#//HSUVStructure/BrakePedal" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BodySubsystem"/>
    <eClassifiers xsi:type="ecore:EClass" name="InteriorSubsystem"/>
    <eClassifiers xsi:type="ecore:EClass" name="LightingSubsystem"/>
    <eClassifiers xsi:type="ecore:EClass" name="ChassisSubsytem">
      <eStructuralFeatures xsi:type="ecore:EReference" name="wheelHubAssembly" ordered="false"
          lowerBound="4" upperBound="4" eType="#//HSUVStructure/WheelHubAssembly"
          containment="true"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="HSUVViews" nsURI="http:///HSUVModel/HSUVViews.ecore" nsPrefix="HSUVModel.HSUVViews">
    <eClassifiers xsi:type="ecore:EClass" name="OperationalVIewpoint"/>
    <eClassifiers xsi:type="ecore:EClass" name="PerformanceViewpoint"/>
    <eSubpackages name="OperationalView" nsURI="http:///HSUVModel/HSUVViews/OperationalView.ecore"
        nsPrefix="HSUVModel.HSUVViews.OperationalView"/>
    <eSubpackages name="PerformanceView" nsURI="http:///HSUVModel/HSUVViews/PerformanceView.ecore"
        nsPrefix="HSUVModel.HSUVViews.PerformanceView"/>
  </eSubpackages>
  <eSubpackages name="HSUVInterfaces" nsURI="http:///HSUVModel/HSUVInterfaces.ecore"
      nsPrefix="HSUVModel.HSUVInterfaces"/>
  <eSubpackages name="HSUVRequirements" nsURI="http:///HSUVModel/HSUVRequirements.ecore"
      nsPrefix="HSUVModel.HSUVRequirements">
    <eClassifiers xsi:type="ecore:EClass" name="Performance"/>
  </eSubpackages>
  <eSubpackages name="HSUVAnalysis" nsURI="http:///HSUVModel/HSUVAnalysis.ecore" nsPrefix="HSUVModel.HSUVAnalysis"/>
  <eSubpackages name="AutomotiveValueTypes" nsURI="http:///HSUVModel/AutomotiveValueTypes.ecore"
      nsPrefix="HSUVModel.AutomotiveValueTypes"/>
</ecore:EPackage>
